### PR TITLE
fix: add back support for react 17

### LINKED ISSUE #130: [Bug]: v4.1.0 'use' is not exported from 'react'
### What happened?

Building with Next `pages/` directory with uploadthing v4.1.0 throws this:

```
Attempted import error: 'use' is not exported from 'react' (imported as 'use').

Import trace for requested module:
./node_modules/.pnpm/@uploadthing+react@4.1.0_react-dropzone@14.2.3_react@18.2.0_uploadthing@4.1.0/node_modules/@uploadthing/react/dist/index.mjs
./src/components/form.tsx
```

This is fine with v4.0.0

### What did you expect to happen?

Not error

### Version

4.1.0

### Reproduction Steps

_No response_

### Reproduction Repository

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by juliusmarminge**
🤷🏼

Closes #130 (although I couldn't repro it on React ^18 which it looked like OP was on, this fixes the issue all the way down to React 17)

### CODE REVIEW

File: packages/react/src/useUploadThing.ts [hunk 1]
```diff
@@ -1,4 +1,4 @@
-import { use, useRef, useState } from "react";
```
Comment (juliusmarminge) [inline packages/react/src/useUploadThing.ts:1]: this could be

```ts
import React, { useRef, useState } from "react";

...

const promiseRef = useRef<...>()

...

if (typeof React.use === "function") ...
```

if you want

Comment (markflorkowski) [reply packages/react/src/useUploadThing.ts:1]: As dumb as it is, I do kind of like this better.

Comment (juliusmarminge) [reply packages/react/src/useUploadThing.ts:1]: Aight changed it up

**Review by markflorkowski — APPROVED** [review]
