### PR TITLE
fix: nuxt module options

### LINKED ISSUE #1047: docs: Nuxt environment variable in setup does not work
### Area of Improvement

I just went through the setup for Nuxt, and it seems like the env var that needs to be set (at least locally) is `UPLOADTHING_TOKEN` not `NUXT_UPLOADTHING_TOKEN` as documented. [The docs](https://docs.uploadthing.com/getting-started/nuxt#add-env-variables) point out that it's very important to use the `NUXT_` prefix, but that doesn't seem to work.

I have not tested this in prod yet, maybe run context matters.

Just a small point of confusion I was able to get through on my own.

Nuxt version: 3.14.159
UploadThing version: 7.3.0

### Link to related docs

https://docs.uploadthing.com/getting-started/nuxt#add-env-variables

### Additional information

_No response_

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

### PR DESCRIPTION
**Pull request by juliusmarminge**
Closes #1047 

Incorporates https://github.com/Effect-TS/effect/pull/3833 + manual destruction of module options to work with static analysis

## Summary by CodeRabbit

- **New Features**
	- Enhanced configuration options for the Nuxt module, including new properties for improved customization.
	- Introduced a utility function to improve configuration handling by converting empty strings to `undefined`.

- **Bug Fixes**
	- Resolved an issue in the `@uploadthing/nuxt` module where specified options were not being honored.

- **Dependency Updates**
	- Updated various dependencies across multiple packages to improve stability and performance, including `effect` and `@effect/platform`.

- **Documentation**
	- Minor corrections in type definitions for consistency across modules.

### CODE REVIEW

File: packages/nuxt/src/module.ts [hunk 1]
```diff
@@ -46,6 +46,13 @@ export default defineNuxtModule<ModuleOptions>({
   defaults: {
     routerPath: "~/server/uploadthing",
     injectStyles: true,
+    // Need to manually set these for static analysis to work, even if they're set to undefined
+    token: undefined,
+    isDev: undefined,
+    logLevel: undefined,
```
Comment (markflorkowski) [inline packages/nuxt/src/module.ts:52]: Should we set a default log level?

**Review by markflorkowski — APPROVED** [review]

File: packages/nuxt/src/module.ts (hunk 1 above)
Comment (juliusmarminge) [reply packages/nuxt/src/module.ts:52]: it's set by core package
