### PR TITLE
fix: accept literals instead of labels

### LINKED ISSUE #1163: [bug]: Expected a log level but received Warning
### Provide environment information

```bash
System:
    OS: Linux 6.11 Ubuntu 24.04.2 LTS 24.04.2 LTS (Noble Numbat)
    CPU: (16) x64 13th Gen Intel(R) Core(TM) i5-13500H
    Memory: 17.42 GB / 31.09 GB
    Container: Yes
    Shell: 5.2.21 - /bin/bash
  Binaries:
    Node: 22.14.0 - ~/.nvm/versions/node/v22.14.0/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v22.14.0/bin/yarn
    npm: 11.1.0 - ~/.nvm/versions/node/v22.14.0/bin/npm
    pnpm: 10.5.2 - ~/.nvm/versions/node/v22.14.0/bin/pnpm
  Browsers:
    Chrome: 133.0.6943.141
  npmPackages:
    @uploadthing/react: ^7.3.0 => 7.3.0 
    typescript: <5.6.0 => 5.5.4 
    uploadthing: ^7.5.2 => 7.5.2
```

### Describe the bug

I'm not able to change log level.

### Link to reproduction

https://stackblitz.com/edit/github-gbrjgmic-urmuitxq

### To reproduce

1. Set log level to "Warning" in `createRouteHandler` at `src/app/api/uploadthing/route.ts`.

```ts
import { createRouteHandler } from "uploadthing/next";
import { fileRouter } from "./core";

export const { GET, POST } = createRouteHandler({
  router: fileRouter,
  config: { logLevel: "Warning" }, // here
});
```
2. Select a file from and start upload.
3. The error will occurs in the running terminal.

### Additional information

_No response_

### 👨‍👧‍👦 Contributing

- [x] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by juliusmarminge**
Closes #1163 

`Config.logLevel` accepts a label and not a literal, but have gotten a hint that this will change in Effect 4.0 so instead of changing our types to match the current behavior, I figured we'll just start accepting literals

## Summary by CodeRabbit

- **Bug Fixes**
  - Fixed an issue with logging configuration validation to ensure only valid log levels are accepted.

- **New Features**
  - Introduced enhanced error handling for logging settings, defaulting to a standard log level when provided values are invalid.
  - Added a new function for improved mapping of log levels to enhance clarity in configuration.

### CODE REVIEW

File: packages/uploadthing/src/_internal/logger.ts [hunk 1]
```diff
@@ -13,7 +15,28 @@ import { UploadThingError } from "@uploadthing/shared";
 
 import { IsDevelopment } from "./config";
 
-export const withMinimalLogLevel = Config.logLevel("logLevel").pipe(
+/**
+ * Config.logLevel counter-intuitively accepts LogLevel["label"]
+ * instead of a literal, ripping it and changing to accept literal
+ */
+export const ConfigLogLevel = (
```
Comment (juliusmarminge) [inline packages/uploadthing/src/_internal/logger.ts:22]: this is taken from the official `Config.logLevel` and just change to accept literal instead.

see https://github.com/Effect-TS/effect/blob/a55835a5c564b19222c728c9ca8beb145066a2a5/packages/effect/src/internal/config.ts#L296-L305

**Review by markflorkowski — APPROVED** [review]
