### PR TITLE
fix: don't use sse

### LINKED ISSUE #474: [bug]: Issue with Package in Production Environment
### Provide environment information

```bash
System:
    OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (6) x64 Intel(R) Xeon(R) CPU @ 2.20GHz
    Memory: 9.80 GB / 13.66 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 20.8.1 - /usr/bin/node
    npm: 10.2.3 - /usr/bin/npm
    pnpm: 8.9.0 - ~/.local/share/pnpm/pnpm
  npmPackages:
    @uploadthing/react: ^6.0.0 => 6.0.0 
    typescript: ^5.2.2 => 5.2.2 
    uploadthing: ^6.0.1 => 6.0.1
```

### Describe the bug

While the package works seamlessly in development mode, allowing successful file uploads with the associated onUploadComplete callback execution, the same functionality fails in production mode.

In the production environment, the package successfully uploads the file; however, the onUploadComplete callback does not execute as expected. Additionally, the request seems to linger in a pending state without progressing further.

image

### Link to reproduction

https://docs.uploadthing.com/getting-started/appdir

### To reproduce

Excecute in Production

### Additional information

_No response_

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #475: [bug]: Production Environment - Error 504
### Provide environment information

```bash
System:
    OS: Linux 6.1 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (8) x64 Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz
    Memory: 12.28 GB / 14.16 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 20.9.0 - ~/.config/nvm/versions/node/v20.9.0/bin/node
    npm: 10.1.0 - ~/.config/nvm/versions/node/v20.9.0/bin/npm
    bun: 1.0.7 - /usr/local/bin/bun
  npmPackages:
    @uploadthing/react: ^6.0.0 => 6.0.0 
    typescript: ^5.1.6 => 5.2.2 
    uploadthing: ^6.0.1 => 6.0.1
```

### Describe the bug

In my dev environment, Uploadthing works exactly as expected.
In my production environment, however, I'm having a bug, without much useful context:

Something went wrong. Please contact UploadThing and provide the following cause: SyntaxError: Unexpected token 'A', "An error o"... is not valid JSON

I'm reporting as the bug message told me to.
It's 3am for me and I don't want to dig any deeper right now but I'll try and look into it properly in the next few days.

If anyone else has encountered this, in the meantime, please let me know :_

### Link to reproduction

https://mrdn.vercel.app

### To reproduce

Log in via Discord or Auth0, go to:

https://mrdn.vercel.app/dashboard/new-listing

Use file uploader.

See error

### Additional information

Weirdly enough, It seems as though the files are indeed being uploaded (I can see them on the uploadthing dashboard)
so I'm assuming the issue is something to do with the callbacks 

Also, in case it helps.

It seems as though I'm getting a 504 from uploadthings api.

Then, my server-side logs (from Vercel) show the file succesfully uploaded.

Then, there is a 10second timeout.

image

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by juliusmarminge**
Closes #474
Closes #475 

Using SSE causes some race conditions we don't wanna deal with and sometimes causes the polling request to time out. Using a callback instead as discussed

### CODE REVIEW

**Comment by juliusmarminge** [comment]
Current dependencies on/for this PR:
* main
  * **PR #480** <a href="https://app.graphite.dev/github/pr/pingdotgg/uploadthing/480?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/pingdotgg/uploadthing/480?utm_source=stack-comment).

**Review by markflorkowski — APPROVED** [review]

File: packages/uploadthing/src/client.ts [hunk 1]
```diff
@@ -184,11 +195,24 @@ export const DANGEROUS__uploadFiles = async <
...
+            callbackData: inferEndpointOutput<TRouter[TEndpoint]>;
+          }
+        | { status: "still waiting" };
+
+      const res = await fetch(pollingUrl, {
+        headers: { authorization: pollingJwt },
+      }).then((r) => r.json() as Promise<PollingResponse>);
+
+      // eslint-disable-next-line @typescript-eslint/no-unsafe-return
+      return res.status === "done" ? res.callbackData : undefined;
```
Comment (markflorkowski) [inline packages/uploadthing/src/client.ts:214]: Can't you always return `res.callbackData`? if `status !== done` it would be undefined anyway?

Comment (juliusmarminge) [reply packages/uploadthing/src/client.ts:214]: ts narrowing callbackData doesnt exist on res if status isnt done, but could adjust type

**Review by t3dotgg — APPROVED** [review]
